# Generated by Django 3.0.5 on 2020-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200402_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
